ALTER TABLE alt_signal.feature_snapshot
    ADD COLUMN IF NOT EXISTS return_1h_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS return_4h_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS return_24h_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS return_7d_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS return_30d_pct DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS volume_ratio_24h DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS return_24h_percentile DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS return_7d_percentile DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS trade_candidate BOOLEAN NOT NULL DEFAULT FALSE;
